spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_NAME}
    username: ${PG_USER}
    password: ${PG_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # disable automatic schema generation
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
