FROM quay.io/keycloak/keycloak:26.3.3

# Bake DB vendor into the build (this is the build-time option)
ENV KC_DB=postgres

# Run build step once in the image
RUN /opt/keycloak/bin/kc.sh build

# Runtime entrypoint: only start, optimized
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]