services:
  postgres:
    image: postgres:16
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - life_balance

  auth:
    image: quay.io/keycloak/keycloak:26.0.2
    command: start --optimized --http-enabled=true
    depends_on: [ postgres ]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_NAME}"
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASS}
      KC_DB_SCHEMA: auth
      KC_HTTP_PORT: ${KC_PORT}
    ports:
      - "${KC_PORT}:${KC_PORT}"
    networks:
      - life_balance
volumes:
  pgdata:

networks:
  life_balance: