services:
  postgres:
    image: postgres:16
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASS}
      PG_LB_USER: ${PG_LB_USER}
      PG_LB_PASS: ${PG_LB_PASS}
      PG_AUTH_USER: ${PG_AUTH_USER}
      PG_AUTH_PASS: ${PG_AUTH_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - life_balance

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    depends_on: [ postgres ]
    environment:
      KEYCLOAK_ADMIN: ${AUTH_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${AUTH_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:${PG_PORT}/${PG_NAME}"
      KC_DB_USERNAME: ${PG_AUTH_USER}
      KC_DB_PASSWORD: ${PG_AUTH_PASS}
      KC_DB_SCHEMA: auth
      KC_HTTP_PORT: ${AUTH_PORT}
      KC_HOSTNAME: "http://${PG_HOST}:${AUTH_PORT}"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "${AUTH_PORT}:8080"
    networks:
      - life_balance
volumes:
  pgdata:

networks:
  life_balance: