#!/bin/bash
set -e

# Required environment variables
required_vars=(
  POSTGRES_USER
  POSTGRES_DB
  PG_LB_USER
  PG_LB_PASS
  PG_AUTH_USER
  PG_AUTH_PASS
)

for v in "${required_vars[@]}"; do
  if [ -z "${!v}" ]; then
    echo "Missing env var: $v"
    exit 1
  fi
done

# Create application user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$PG_LB_USER') THEN
      CREATE USER $PG_LB_USER WITH PASSWORD '$PG_LB_PASS';
    END IF;
  END
  \$\$;
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $PG_LB_USER;
EOSQL

# --- Create auth user (dedicated auth schema) ---
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$PG_AUTH_USER') THEN
      CREATE USER $PG_AUTH_USER WITH PASSWORD '$PG_AUTH_PASS';
    END IF;
  END
  \$\$;
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $PG_AUTH_USER;
EOSQL

# Grant schema and object privileges
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  GRANT USAGE, CREATE ON SCHEMA public TO $PG_LB_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $PG_LB_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $PG_LB_USER;

  CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION $PG_LB_USER;
  CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION $PG_AUTH_USER;

  GRANT USAGE, CREATE ON SCHEMA core TO $PG_LB_USER;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO $PG_LB_USER;

  GRANT USAGE, CREATE ON SCHEMA auth TO $PG_AUTH_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO $PG_AUTH_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA core
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $PG_LB_USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA auth
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $PG_AUTH_USER;

EOSQL
